#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libexif
Version  : 0.6.21
Release  : 5
URL      : http://downloads.sourceforge.net/project/libexif/libexif/0.6.21/libexif-0.6.21.tar.bz2
Source0  : http://downloads.sourceforge.net/project/libexif/libexif/0.6.21/libexif-0.6.21.tar.bz2
Summary  : EXIF tag library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libexif-lib
Requires: libexif-doc
Requires: libexif-locales
Patch1: cve-2017-7544.patch

%description
libexif is a library for parsing, editing, and saving EXIF data. It is
intended to replace lots of redundant implementations in command-line
utilities and programs with GUIs.

%package dev
Summary: dev components for the libexif package.
Group: Development
Requires: libexif-lib
Provides: libexif-devel

%description dev
dev components for the libexif package.


%package doc
Summary: doc components for the libexif package.
Group: Documentation

%description doc
doc components for the libexif package.


%package lib
Summary: lib components for the libexif package.
Group: Libraries

%description lib
lib components for the libexif package.


%package locales
Summary: locales components for the libexif package.
Group: Default

%description locales
locales components for the libexif package.


%prep
%setup -q -n libexif-0.6.21
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507235289
export CFLAGS="$CFLAGS -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fstack-protector-strong "
export FFLAGS="$CFLAGS -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong "
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1507235289
rm -rf %{buildroot}
%make_install
%find_lang libexif-12

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libexif/_stdint.h
/usr/include/libexif/exif-byte-order.h
/usr/include/libexif/exif-content.h
/usr/include/libexif/exif-data-type.h
/usr/include/libexif/exif-data.h
/usr/include/libexif/exif-entry.h
/usr/include/libexif/exif-format.h
/usr/include/libexif/exif-ifd.h
/usr/include/libexif/exif-loader.h
/usr/include/libexif/exif-log.h
/usr/include/libexif/exif-mem.h
/usr/include/libexif/exif-mnote-data.h
/usr/include/libexif/exif-tag.h
/usr/include/libexif/exif-utils.h
/usr/lib64/libexif.so
/usr/lib64/pkgconfig/libexif.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libexif/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libexif.so.12
/usr/lib64/libexif.so.12.3.3

%files locales -f libexif-12.lang
%defattr(-,root,root,-)

